"""empty message

Revision ID: f6b945117232
Revises: 
Create Date: 2021-06-28 00:18:24.459315

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f6b945117232'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_fk_film_id', table_name='inventory')
    op.drop_index('idx_store_id_film_id', table_name='inventory')
    op.drop_table('inventory')
    op.drop_index('idx_fk_country_id', table_name='city')
    op.drop_table('city')
    op.drop_index('idx_fk_address_id', table_name='store')
    op.drop_index('idx_unique_manager', table_name='store')
    op.drop_table('store')
    op.drop_index('idx_title_description', table_name='film_text')
    op.drop_table('film_text')
    op.drop_index('idx_fk_address_id', table_name='customer')
    op.drop_index('idx_fk_store_id', table_name='customer')
    op.drop_index('idx_last_name', table_name='customer')
    op.drop_table('customer')
    op.drop_table('language')
    op.drop_index('idx_fk_film_id', table_name='film_actor')
    op.drop_table('film_actor')
    op.drop_index('idx_fk_address_id', table_name='staff')
    op.drop_index('idx_fk_store_id', table_name='staff')
    op.drop_table('staff')
    op.drop_table('country')
    op.drop_index('idx_fk_city_id', table_name='address')
    op.drop_index('idx_location', table_name='address')
    op.drop_table('address')
    op.drop_table('category')
    op.drop_index('idx_fk_customer_id', table_name='payment')
    op.drop_index('idx_fk_staff_id', table_name='payment')
    op.drop_table('payment')
    op.drop_index('idx_fk_customer_id', table_name='rental')
    op.drop_index('idx_fk_inventory_id', table_name='rental')
    op.drop_index('idx_fk_staff_id', table_name='rental')
    op.drop_index('rental_date', table_name='rental')
    op.drop_table('rental')
    op.drop_index('idx_actor_last_name', table_name='actor')
    op.drop_table('actor')
    op.drop_index('idx_fk_language_id', table_name='film')
    op.drop_index('idx_fk_original_language_id', table_name='film')
    op.drop_index('idx_title', table_name='film')
    op.drop_table('film')
    op.drop_table('film_category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('film_category',
    sa.Column('film_id', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('category_id', mysql.TINYINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], name='fk_film_category_category', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['film_id'], ['film.film_id'], name='fk_film_category_film', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('film_id', 'category_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('film',
    sa.Column('film_id', mysql.SMALLINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('release_year', mysql.YEAR(), nullable=True),
    sa.Column('language_id', mysql.TINYINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('original_language_id', mysql.TINYINT(unsigned=True), autoincrement=False, nullable=True),
    sa.Column('rental_duration', mysql.TINYINT(unsigned=True), server_default=sa.text("'3'"), autoincrement=False, nullable=False),
    sa.Column('rental_rate', mysql.DECIMAL(precision=4, scale=2), server_default=sa.text("'4.99'"), nullable=False),
    sa.Column('length', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=True),
    sa.Column('replacement_cost', mysql.DECIMAL(precision=5, scale=2), server_default=sa.text("'19.99'"), nullable=False),
    sa.Column('rating', mysql.ENUM('G', 'PG', 'PG-13', 'R', 'NC-17'), server_default=sa.text("'G'"), nullable=True),
    sa.Column('special_features', mysql.SET(length=17), nullable=True),
    sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['language.language_id'], name='fk_film_language', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['original_language_id'], ['language.language_id'], name='fk_film_language_original', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('film_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_title', 'film', ['title'], unique=False)
    op.create_index('idx_fk_original_language_id', 'film', ['original_language_id'], unique=False)
    op.create_index('idx_fk_language_id', 'film', ['language_id'], unique=False)
    op.create_table('actor',
    sa.Column('actor_id', mysql.SMALLINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('actor_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_actor_last_name', 'actor', ['last_name'], unique=False)
    op.create_table('rental',
    sa.Column('rental_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rental_date', mysql.DATETIME(), nullable=False),
    sa.Column('inventory_id', mysql.MEDIUMINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('customer_id', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('return_date', mysql.DATETIME(), nullable=True),
    sa.Column('staff_id', mysql.TINYINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], name='fk_rental_customer', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.inventory_id'], name='fk_rental_inventory', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], name='fk_rental_staff', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('rental_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('rental_date', 'rental', ['rental_date', 'inventory_id', 'customer_id'], unique=False)
    op.create_index('idx_fk_staff_id', 'rental', ['staff_id'], unique=False)
    op.create_index('idx_fk_inventory_id', 'rental', ['inventory_id'], unique=False)
    op.create_index('idx_fk_customer_id', 'rental', ['customer_id'], unique=False)
    op.create_table('payment',
    sa.Column('payment_id', mysql.SMALLINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('customer_id', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('staff_id', mysql.TINYINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('rental_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', mysql.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('payment_date', mysql.DATETIME(), nullable=False),
    sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], name='fk_payment_customer', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rental_id'], ['rental.rental_id'], name='fk_payment_rental', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], name='fk_payment_staff', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('payment_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_fk_staff_id', 'payment', ['staff_id'], unique=False)
    op.create_index('idx_fk_customer_id', 'payment', ['customer_id'], unique=False)
    op.create_table('category',
    sa.Column('category_id', mysql.TINYINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('category_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('address',
    sa.Column('address_id', mysql.SMALLINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('address', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('address2', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('district', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('city_id', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('postal_code', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('location', sa.NullType(), nullable=False),
    sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.city_id'], name='fk_address_city', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('address_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_location', 'address', ['location'], unique=False)
    op.create_index('idx_fk_city_id', 'address', ['city_id'], unique=False)
    op.create_table('country',
    sa.Column('country_id', mysql.SMALLINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('country', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('country_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('staff',
    sa.Column('staff_id', mysql.TINYINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('address_id', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('picture', sa.BLOB(), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('store_id', mysql.TINYINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('password', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=40), nullable=True),
    sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address.address_id'], name='fk_staff_address', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['store_id'], ['store.store_id'], name='fk_staff_store', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('staff_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_fk_store_id', 'staff', ['store_id'], unique=False)
    op.create_index('idx_fk_address_id', 'staff', ['address_id'], unique=False)
    op.create_table('film_actor',
    sa.Column('actor_id', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('film_id', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.actor_id'], name='fk_film_actor_actor', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['film_id'], ['film.film_id'], name='fk_film_actor_film', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('actor_id', 'film_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_fk_film_id', 'film_actor', ['film_id'], unique=False)
    op.create_table('language',
    sa.Column('language_id', mysql.TINYINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', mysql.CHAR(length=20), nullable=False),
    sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('language_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('customer',
    sa.Column('customer_id', mysql.SMALLINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('store_id', mysql.TINYINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('address_id', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('create_date', mysql.DATETIME(), nullable=False),
    sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.address_id'], name='fk_customer_address', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['store_id'], ['store.store_id'], name='fk_customer_store', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('customer_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_last_name', 'customer', ['last_name'], unique=False)
    op.create_index('idx_fk_store_id', 'customer', ['store_id'], unique=False)
    op.create_index('idx_fk_address_id', 'customer', ['address_id'], unique=False)
    op.create_table('film_text',
    sa.Column('film_id', mysql.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('film_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_title_description', 'film_text', ['title', 'description'], unique=False)
    op.create_table('store',
    sa.Column('store_id', mysql.TINYINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('manager_staff_id', mysql.TINYINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('address_id', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address.address_id'], name='fk_store_address', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['manager_staff_id'], ['staff.staff_id'], name='fk_store_staff', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('store_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_unique_manager', 'store', ['manager_staff_id'], unique=False)
    op.create_index('idx_fk_address_id', 'store', ['address_id'], unique=False)
    op.create_table('city',
    sa.Column('city_id', mysql.SMALLINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('city', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('country_id', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.country_id'], name='fk_city_country', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('city_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_fk_country_id', 'city', ['country_id'], unique=False)
    op.create_table('inventory',
    sa.Column('inventory_id', mysql.MEDIUMINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('film_id', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('store_id', mysql.TINYINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['film.film_id'], name='fk_inventory_film', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['store_id'], ['store.store_id'], name='fk_inventory_store', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('inventory_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_store_id_film_id', 'inventory', ['store_id', 'film_id'], unique=False)
    op.create_index('idx_fk_film_id', 'inventory', ['film_id'], unique=False)
    # ### end Alembic commands ###
